### PR TITLE
:beetle: Add debug mode

### PR DESCRIPTION
**Pull request by nkreshchenko**
* add new code lens `Debug Test`
* add new command `javascript-test-runner.debug.test`

### CODE REVIEW

**Comment by nkreshchenko** [comment]
Demo screeshoot
extension development host - fa ts rest-api-v2 2018-04-20 00-42-14

**Comment by g3offrey** [comment]
Hi,
first of all I want to say good job and thank you for your awesome work 🥇 
I think you just built a must-have feature 💯 

Could you please just delete the `package-lock.json` as there is already a `yarn.lock` ?
After that I would be able to merge it and create a new release to share your work with everybody 👍 

PS : Please accept my apologies for taking some time to answer your pull request 😞

**Comment by ooga** [comment]
It will be nice to add the jest parameters `--runInBand` to to make debug easier

https://facebook.github.io/jest/docs/en/cli.html#runinband

**Comment by g3offrey** [comment]
@ooga you totally right ! 
good job for thinking about that 💯 

@nkreshchenko is it ok to add it on your PR ? 😅

**Comment by nkreshchenko** [comment]
@g3offrey ok, I'll do it in 1-2 days

**Comment by g3offrey** [comment]
nice @nkreshchenko thank you very much 👍 
(don't waste too much of your free time for that, and rest yourself this is more important than closing this PR in urgence 😅)

**Comment by fallanic** [comment]
I was considering forking / sending a PR for the same feature, looking forward to it!

Thanks everyone for the great work :+1:

**Pull request merged**
