### PR TITLE
Improve test detection

### LINKED ISSUE #22: Improve test case detection
At the moment every file is parsed to detect if it's a mocha or jest test case (Token based detection).

Maybe it would be better to parse just files that fulfill the criteria of the framework:

### Mocha

Mocha expects tests normally in folder `test. Instead parsing all files, only files located in a sub folder of `test`could be parsed.

Since it's possible to change the default folder location with a CLI option it should be possible to configure this path.

### Jest

Tests are found by Jest by matching files against a configured regex in either

- [testMatch](https://jestjs.io/docs/en/configuration.html#testmatch-array-string)
or
- [testRegex](https://jestjs.io/docs/en/configuration.html#testregex-string)

This options can set in `package.json`, `jest.config.js` file or or through the `--config <path/to/js|json>` CLI option.

`jest --showConfig` will return the current active configuration as JSON string.

### Further improvements

Maybe parsing should also just be activated if a devDependency to mocha or jest exists in `package.json` (Or if file mocha/jest exists in `node_modules/.bin`).

It should be possible to deactivate this detection by config option to support also environments with global installed mocha/jest

### PR DESCRIPTION
**Pull request by roggenbrot**
Resolves #22

### CODE REVIEW

**Comment by roggenbrot** [comment]
First working version of the PR

Known issues:

- If Jest is not installed (yet) via npm install, retrieval of config will fail and editor has to be restarted 
I will add a file watch to node_modules/.bin folder an refresh configuration as soon as some file file was added in the next version.

Could someone test this PR on Windows/Mocha?

**Comment by roggenbrot** [comment]
Done

**Comment by g3offrey** [comment]
Wow what a PR @roggenbrot ! You did an amazing work, good job 💯 

I'll check this as soon as possible (I am a bit busy this month), but I will definitely merge this as it resolves a lot of issues, and potentially improve the performance for users 👌 
I think this also resolves #5 #9 

Thank you very much for your contributions 😄

**Comment by LoveSponge** [comment]
@g3offrey @roggenbrot 
Tested windows/mocha: Still has problem with issue #7 
After changing all references of `rootPath.uri.path` to `rootPath.uri.fsPath` it seems to work perfectly.
PR #27 has a more in depth description of where exactly the above changes must occur.

Could you check that after making the above change that it still works on linux, if so I can confirm your code indeed works.

**Comment by fallanic** [comment]
any update regarding this? I'd love for people in my team to be able to use this awesome extension on windows :)

**Comment by LoveSponge** [comment]
@fallanic The extension works on Windows by applying the above changes to a couple of files.

**Note:** 
You must use Powershell or cmdprompt as NodeJS isn't /wasn't designed to work with Cygwin or something like that.

**Comment by fallanic** [comment]
thanks @LoveSponge I tried changing the `path` to `fsPath` calls on my windows machine and indeed it worked, I was just wondering if we could merge one of these PR (maybe yours for now, because it's focused on that issue only) so other windows user could benefit from it.

This plugin is killer, and a must have for any VS code user in my opinion, it's a shame that windows users can't benefit from it yet :) (so close!)

cc @g3offrey

**Comment by lonix1** [comment]
Any plans to merge this?

**Comment by lonix1** [comment]
?

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080

**Comment by felixjb** [comment]
Hi @roggenbrot , do you want to help us maintain the project? 
I referenced your pull request and I am planning on merging it as soon as possible.

**Pull request closed without merging**
